### ISSUE TITLE
Giving the shell the path to a file or a directory or using ./ says "Command not found."

### ISSUE THREAD

**Issue by Satharus** [Satharus/Chell#11]
This isn't correct. Before checking $PATH for the command input, it should first check if it is a file, directory, or if the input starts with ./ in order to execute it.

**Comment by ptrstr** [comment]
Fixed in PR #12

**Comment by Satharus** [comment]
Thanks a lot, just a note that I think in general it's a better idea to use the POSIX standard's PATH_MAX from limits.h instead.

**Comment by Satharus** [comment]
Updated to POSIX definitions in 8b9fbcb95ad0461c07772654cc18e44d9a2d1891.
