### ISSUE TITLE
Backspace not working properly

### ISSUE THREAD

**Issue by Satharus** [Satharus/Chell#17]
The cursor is not shifted to the right place when using backspace in the middle of a string. While the deleting works, it feels really awkward.

Edit: Please don't use any external libraries, there was a lot of effort put into implementing a minimal readline-like interface which doesn't have external dependencies. 

https://github.com/Satharus/Chell/blob/54ecd43aa55f35f1e17d9522b2e79666d80fd54b/src/chad-readline.c#L52-L83

**Comment by ptrstr** [comment]
Could you assign me to this?

**Comment by Satharus** [comment]
Fixed in #18
