### ISSUE TITLE
Add command history

### ISSUE THREAD

**Issue by Satharus** [Satharus/Chell#3]
Add command history like in BASH where you can use arrow up and arrow down to cycle previously run commands.

**Comment by Parthav46** [comment]
I would like to work on this

**Comment by Parthav46** [comment]
Is it OK if I write the code to handle input in a separate file? The code is looking a bit cluttered. I will also be making a Makefile to easily compile multple files and build the project.

**Comment by Satharus** [comment]
@Parthav46  Sure yeah :D No problems!

**Comment by Satharus** [comment]
@Parthav46  it would be great if you could write the history to a file in the home directory like `~/.chell.history` or something and read it on startup. Kinda like what BASH and zsh do.

I am just suggesting, if you don't want to do it that's fine :D

**Comment by Parthav46** [comment]
I was thinking to do the same

**Comment by Satharus** [comment]
Awesome, I added the hacktoberfest label too incase you're doing the challenge :D

**Comment by Satharus** [comment]
@Parthav46  Hey

Are you still working on this? I am going to work on issue #6 right now which will require me to write a small readline-like implementation. 

I was just wondering if you've made any changes so far so that I could keep them in mind when writing it or maybe not write it all from scratch if you've made any progress with it.

**Comment by Parthav46** [comment]
@Satharus i have created an input function that can handle special key presses all you need to do is implement what the key does. If you like i can make a different PR just for that function.
You can check the code at [f-command-history](https://github.com/Parthav46/Chell/tree/f-command-history) branch in my fork

**Comment by Satharus** [comment]
Awesome! 

If you can, please make a PR just for that function. Thanks a lot :D 


Edit: @Parthav46 I just checked the branch and that's awesome :D! Almost the same as what I was doing right now, it seems that we even stumbled upon the same getch() implementation :smile: 

Could you please make a pull request so that I can refactor the code a little bit and merge it into my readline implementation?

**Comment by Parthav46** [comment]
Just for suggestion I was thinking to create a doubly linked list implementation instead of character array to handle inputs so that it can be edited. But I will do that after I implement command history.

**Comment by Satharus** [comment]
Good suggestion, keep it in mind and we can take a look at it after we finish the history and #6, I am changing some of the stuff in chellin for now and I will tell you once I push them.

**Comment by Parthav46** [comment]
@Satharus I have made this PR. Do check if any corrections are needed.
There are few bugs there which I will try to solve after my day job is done (Mondays ☹️).
