### ISSUE TITLE
"man" won't run

### ISSUE THREAD

**Issue by Satharus** [Satharus/Chell#4]
Running `man man` or `man anything` leads to this output:

`man: can't execute cat: No such file or directory
man: command exited with status 255: (cd /usr/share/man && /usr/lib/man-db/zsoelim) | (cd /usr/share/man && /usr/lib/man-db/manconv -f UTF-8:ISO-8859-1 -t ISO-8859-1//IGNORE) | (cd /usr/share/man && tbl) | (cd /usr/share/man && nroff -mandoc -rLL=120n -rLT=120n -Tutf8)`

**Comment by lordadamson** [comment]
working on it
