### ISSUE TITLE
Ctrl + C exits the shell

### ISSUE THREAD

**Issue by Satharus** [Satharus/Chell#5]
Hitting ctrl + c exits the shell, which isn't standard behaviour. The shill should only exit using exit or q. This input should be handled.

**Comment by Vamsi995** [comment]
Hey i'd like to give this a try

**Comment by lordadamson** [comment]
damn it. I was already working on it. Okay you go lol

**Comment by Satharus** [comment]
#7 Fixed this.
@Vamsi995  Thanks!
