### ISSUE TITLE
Command line interface not editable

### ISSUE THREAD

**Issue by Satharus** [Satharus/Chell#6]
You can't move between the letters using the left and right arrow keys. The characters ^[[D and ^[[C are written instead.

I am trying to keep dependencies to a minimum, so using GNU readline is not an option, sadly.

**Comment by sarvasvaKhare** [comment]
I would like to work on it please assign it to me.

**Comment by dnabre** [comment]
This and #3  are non-trivial code. The libraries readline(gnu) and libedit(bsd) are design to handle this specific task. I'm not saying to give up the goal of avoiding the dependencies, but having nice editable commandline with history is a good hunk of code. 

libedit for example is about 14k lines of C. Not having full support for weird consoles and limiting features could easily drop to a quarter of the size, but the code for just this part is going be more than csh-style shell with pipelines, i/o-redirection, and job control.

**Comment by Satharus** [comment]
@dnabre  Thanks a lot for your clarification. I totally understand that and I am not saying that it is a trivial task. 

Maybe this issue is misleading with the "good first issue" label, hence I removed it.

My point is that since this is a completely educational project with no intent of it being actually used as a shell for a system, I am trying to implement all of it as much as possible using only standard C libraries and of course adhere to the POSIX specific standards (like limits.h and such). 

Again, I am not saying it is a wrong practice to use readline or anything, the whole point of open source software and libraries is to not reinvent the wheel and reuse components which can be used. I hope you get my point.

**Comment by Satharus** [comment]
fixed in 00bb1acb070bc660fa4de4c0a3eb9d4408b6207e.
